abstract class ChatScreenStates{}
class ChatScreenInit extends ChatScreenStates{}
class ChatScreenLoading extends ChatScreenStates{}
class ChatScreenSuccess extends ChatScreenStates{}
class ChatScreenMyData extends ChatScreenStates{}
class ChatScreenUserData extends ChatScreenStates{}
class UpdateChattingWith extends ChatScreenStates{}
class SaveImage extends ChatScreenStates{}
class ChatScreenUpdateAction extends ChatScreenStates{}
class ChatScreenUpdateCounter extends ChatScreenStates{}
class ChatScreenCheckChats extends ChatScreenStates{}
class ChatScreenGetChats extends ChatScreenStates{}
class UpdateUserLastMessage extends ChatScreenStates{}
class UpdateMyLastMessage extends ChatScreenStates{}
class SendUserMessage extends ChatScreenStates{}
class SendMyMessage extends ChatScreenStates{}
class GetMessages extends ChatScreenStates{}
class UpdateMyInfoChat extends ChatScreenStates{}
class UpdateUserInfoChat extends ChatScreenStates{}
class CreateMyChat extends ChatScreenStates{}
class CreateUserChat extends ChatScreenStates{}
class PickImage extends ChatScreenStates{}
class ImageUploadSuccess extends ChatScreenStates{}
class GetUserId extends ChatScreenStates{}
class ChatScreenFailed extends ChatScreenStates{}